name: 'get dependencies'
description: 'get dependencies from npm and cache them'
inputs:
  caching:
    description: 'whether to cache dependencies or not'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'out of cache'
    value: ${{ steps.install.outputs.cache }}
runs:
  using: 'composite'
  steps:
      - name: get code
        uses: actions/checkout@v3
      - name: cache dependencies
        if: inputs.caching == 'true'
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        id: install
        if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
        run: |
          npm ci
          echo "::set-output name=cache::'${{ inputs.caching }}'"
        shell: bash